# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g1_lpc', '0002_remove_agenda_institucional'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoa',
            new_name='Usuario',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='pessoa',
            new_name='usuario',
        ),
    ]
