# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('g1_lpc', '0003_auto_20170925_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(verbose_name='nome')),
                ('Compromisso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='g1_lpc.Compromisso')),
                ('convidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='g1_lpc.Usuario')),
            ],
        ),
    ]
