# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('g1_lpc', '0004_convite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta_Convite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceite', models.BooleanField(verbose_name='aceite')),
                ('convidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='g1_lpc.Convite')),
            ],
        ),
    ]
